server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:

      spring:
        datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc://postgresql://ec2-18-209-169-66.compute-1.amazonaws.com:5432/d8vtdpf3k0rg3u
          username: fskwcicfluvzks
          password: 33242715b8ef7c7b4382d4c8af27bd2a722c3cb131eb9ec6900b58be4babfca1
          platform: postgres
        jpa:
          hibernate:
            ddl-auto: create-drop
          generate-ddl: true